
package com.github.jordane_quincy.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Tue May 16 08:25:44 CEST 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "toPrint", namespace = "http://com.github.jordane_quincy")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toPrint", namespace = "http://com.github.jordane_quincy")

public class ToPrint {

    @XmlElement(name = "toPrint")
    private java.lang.String toPrint;

    public java.lang.String getToPrint() {
        return this.toPrint;
    }

    public void setToPrint(java.lang.String newToPrint)  {
        this.toPrint = newToPrint;
    }

}

