
package com.github.jordane_quincy.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Tue Apr 25 09:30:25 CEST 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "toPrintResponse", namespace = "http://com.github.jordane_quincy")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toPrintResponse", namespace = "http://com.github.jordane_quincy")

public class ToPrintResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

