package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-24T09:13:36.778+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "BankService", 
                  wsdlLocation = "file:/C:/Users/Jordane/Documents/GitHub/M2_notere_soap/m2_notere_soap/WebContent/wsdl/bankserviceimpl.wsdl",
                  targetNamespace = "http://com.github.jordane_quincy") 
public class BankService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://com.github.jordane_quincy", "BankService");
    public final static QName BankServiceItf = new QName("http://com.github.jordane_quincy", "BankServiceItf");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Jordane/Documents/GitHub/M2_notere_soap/m2_notere_soap/WebContent/wsdl/bankserviceimpl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Jordane/Documents/GitHub/M2_notere_soap/m2_notere_soap/WebContent/wsdl/bankserviceimpl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BankService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BankServiceItf
     */
    @WebEndpoint(name = "BankServiceItf")
    public BankServiceItf getBankServiceItf() {
        return super.getPort(BankServiceItf, BankServiceItf.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankServiceItf
     */
    @WebEndpoint(name = "BankServiceItf")
    public BankServiceItf getBankServiceItf(WebServiceFeature... features) {
        return super.getPort(BankServiceItf, BankServiceItf.class, features);
    }

}
