package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-24T09:13:36.767+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://com.github.jordane_quincy", name = "BankServiceItf")
@XmlSeeAlso({ObjectFactory.class})
public interface BankServiceItf {

    @WebMethod
    @RequestWrapper(localName = "toPrint", targetNamespace = "http://com.github.jordane_quincy", className = "client.ToPrint")
    @ResponseWrapper(localName = "toPrintResponse", targetNamespace = "http://com.github.jordane_quincy", className = "client.ToPrintResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String toPrint(
        @WebParam(name = "toPrint", targetNamespace = "")
        java.lang.String toPrint
    );
}
