
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-24T09:13:36.751+02:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankService",
                      portName = "BankServiceItf",
                      targetNamespace = "http://com.github.jordane_quincy",
                      wsdlLocation = "file:/C:/Users/Jordane/Documents/GitHub/M2_notere_soap/m2_notere_soap/WebContent/wsdl/bankserviceimpl.wsdl",
                      endpointInterface = "client.BankServiceItf")
                      
public class BankServiceItfImpl implements BankServiceItf {

    private static final Logger LOG = Logger.getLogger(BankServiceItfImpl.class.getName());

    /* (non-Javadoc)
     * @see client.BankServiceItf#toPrint(java.lang.String toPrint)*
     */
    public java.lang.String toPrint(java.lang.String toPrint) { 
        LOG.info("Executing operation toPrint");
        System.out.println(toPrint);
        try {
            java.lang.String _return = "_return247184463";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
