
package jordane_quincy.github.com;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.10 2017-05-16T08:43:50.673+02:00
 * Generated source version: 3.1.10
 *
 */
public final class BankServiceItf_BankServiceItf_Client {

	private static final QName SERVICE_NAME = new QName("http://com.github.jordane_quincy", "BankService");

	private BankServiceItf_BankServiceItf_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = BankService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		BankService ss = new BankService(wsdlURL, SERVICE_NAME);
		BankServiceItf port = ss.getBankServiceItf();

		{
			System.out.println("Invoking debit...");
			java.lang.String _debit_idCompteADebiter = "2";
			java.lang.String _debit_montant = "10";
			java.lang.String _debit__return = port.debit(_debit_idCompteADebiter, _debit_montant);
			System.out.println("debit de " + _debit_montant + " sur le compte id " + _debit_idCompteADebiter
					+ ", debit.result=" + _debit__return);

			// Expected result :
			// <RetourWS><idCompteDebite>2</idCompteDebite><idCompteCredite>1</idCompteCredite><typeOperation>transfert</typeOperation><montant>10</montant></RetourWS>

		}
		{
			System.out.println("Invoking remboursement...");
			java.lang.String _remboursement_idCompteACrediter = "2";
			java.lang.String _remboursement_montant = "5";
			java.lang.String _remboursement__return = port.remboursement(_remboursement_idCompteACrediter,
					_remboursement_montant);
			System.out.println("remboursement de " + _remboursement_montant + " sur le compte id "
					+ _remboursement_idCompteACrediter + ", remboursement.result=" + _remboursement__return);

			// Expected result :
			// <RetourWS><idCompteDebite>1</idCompteDebite><idCompteCredite>2</idCompteCredite><typeOperation>transfert</typeOperation><montant>5</montant></RetourWS>
		}
		{
			System.out.println("Invoking toPrint...");
			java.lang.String _toPrint_toPrint = "désolé pour ce TP de piètre qualité";
			java.lang.String _toPrint__return = port.toPrint(_toPrint_toPrint);
			System.out.println("toPrint.result=" + _toPrint__return);

			// Expected result :
			// toPrint.result=désolé pour ce TP de piètre qualité

		}

		System.exit(0);
	}

}
