
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package jordane_quincy.github.com;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-16T08:43:50.748+02:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankService",
                      portName = "BankServiceItf",
                      targetNamespace = "http://com.github.jordane_quincy",
                      wsdlLocation = "file:/C:/Users/Jordane/Documents/GitHub/M2_notere_soap/m2_notere_soap/WebContent/wsdl/bankserviceimpl.wsdl",
                      endpointInterface = "jordane_quincy.github.com.BankServiceItf")
                      
public class BankServiceItfImpl implements BankServiceItf {

    private static final Logger LOG = Logger.getLogger(BankServiceItfImpl.class.getName());

    /* (non-Javadoc)
     * @see jordane_quincy.github.com.BankServiceItf#debit(java.lang.String idCompteADebiter, java.lang.String montant)*
     */
    public java.lang.String debit(java.lang.String idCompteADebiter, java.lang.String montant) { 
        LOG.info("Executing operation debit");
        System.out.println(idCompteADebiter);
        System.out.println(montant);
        try {
            java.lang.String _return = "_return-1037703583";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jordane_quincy.github.com.BankServiceItf#remboursement(java.lang.String idCompteACrediter, java.lang.String montant)*
     */
    public java.lang.String remboursement(java.lang.String idCompteACrediter, java.lang.String montant) { 
        LOG.info("Executing operation remboursement");
        System.out.println(idCompteACrediter);
        System.out.println(montant);
        try {
            java.lang.String _return = "_return1150049606";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jordane_quincy.github.com.BankServiceItf#toPrint(java.lang.String toPrint)*
     */
    public java.lang.String toPrint(java.lang.String toPrint) { 
        LOG.info("Executing operation toPrint");
        System.out.println(toPrint);
        try {
            java.lang.String _return = "_return-2137015097";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
