package jordane_quincy.github.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-16T08:43:50.771+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://com.github.jordane_quincy", name = "BankServiceItf")
@XmlSeeAlso({ObjectFactory.class})
public interface BankServiceItf {

    @WebMethod
    @RequestWrapper(localName = "debit", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.Debit")
    @ResponseWrapper(localName = "debitResponse", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.DebitResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String debit(
        @WebParam(name = "idCompteADebiter", targetNamespace = "")
        java.lang.String idCompteADebiter,
        @WebParam(name = "montant", targetNamespace = "")
        java.lang.String montant
    );

    @WebMethod
    @RequestWrapper(localName = "remboursement", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.Remboursement")
    @ResponseWrapper(localName = "remboursementResponse", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.RemboursementResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String remboursement(
        @WebParam(name = "idCompteACrediter", targetNamespace = "")
        java.lang.String idCompteACrediter,
        @WebParam(name = "montant", targetNamespace = "")
        java.lang.String montant
    );

    @WebMethod
    @RequestWrapper(localName = "toPrint", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.ToPrint")
    @ResponseWrapper(localName = "toPrintResponse", targetNamespace = "http://com.github.jordane_quincy", className = "jordane_quincy.github.com.ToPrintResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String toPrint(
        @WebParam(name = "toPrint", targetNamespace = "")
        java.lang.String toPrint
    );
}
